### ISSUE TITLE
 Command script - does not exist

### ISSUE THREAD

**Issue by cjeje84** [Orion-Entertainment/MaldenLifeServer#1]
Hello I have a problem in wanting to start my server it gives me its errors and restarts the server in loop yet they are indicated in the file CfgRemoteExec in the right place.

Would you be why please thank you in advance.

`Scripting command 'playSounds' does not exist
Scripting command 'clientSound' does not exist
Scripting command 'notificationSystem' does not exist`

**Comment by plusflabby** [comment]
Post the full rpt log
